build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related Dev APIs "
  contactDetails:
    name: "Smitha Ray - Dev Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 369-3659
    - (125) 987-6358